---
- hosts: bastion
  remote_user: jerred
  roles:
    - users
    - sudo
    - role: ansible-secure-ssh
      become: yes
      ssh_user: jerred
      ssh_identity_key: files/id_rsa.pub
    - ufw
    - role: jnv.unattended-upgrades
      become: yes
      unattended_automatic_reboot: true
      unattended_remove_unused_dependencies: true
      unattended_mail: jerred
      unattended_origins_patterns:
        - origin=Debian,codename=${distro_codename}
        - label=Debian-Security
